version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: nisheethshah
      MONGO_INITDB_ROOT_PASSWORD: xvrnJ8iW35FYC671
      MONGO_INITDB_DATABASE: coding_assignment

  app:
    build: .
    container_name: python_app
    depends_on:
      - mongo
    volumes:
      - .:/app
    ports:
      - "5000:80"
    environment:
      MONGO_URI: mongodb+srv://nisheethshah:xvrnJ8iW35FYC671@codingassignment.fmfbgrn.mongodb.net/?retryWrites=true&w=majority&appName=CodingAssignment
    command: python main.py